## Use-case: A shopping mall giant has hired you as a DAta scientist. Your job is to create a model that can predict whether the customer will purchase the product from my website based on customer's age and estimated salary

In [1]:
import numpy as np
import pandas as pd

In [2]:
purchaseDataDF = pd.read_csv('Social_Network_Ads.csv')

In [3]:
purchaseDataDF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


## Rule for Classification w.r.t. sklearn

#### 1. Features myst be in 2D
#### 2. Label must be in 1D in case of supervised classification problem, this is the requirement of Sklearn 
#### ( Incase regression nonclassification problem Label should be in 2d
#### when we use sklearn package, this is the requirement of sklearn)

In [4]:
#Seperate our data as features and label
featuresDF = purchaseDataDF.iloc[:,[2,3]].values # by default this will be 2d
labelDF = purchaseDataDF.iloc[:,4].values        # by default this will be 1d
# labelDF = purchaseDataDF.iloc[:, -1]

In [5]:
purchaseDataDF

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [6]:
featuresDF.shape

(400, 2)

In [7]:
#featuresDF

In [8]:
labelDF.shape

(400,)

In [9]:
#labelDF

In [10]:
labelDF.ndim

1

# 1.  Train Test Split
#### -For Generalization of data..means Generalization is all about how the model performs with UNKNOWN DATA

In [14]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(featuresDF,
                                                labelDF,
                                                test_size=0.2,
                                                random_state=10)

In [22]:
# X_train

In [19]:
X_train,X_test,y_train,y_test = train_test_split(featuresDF,
                                                labelDF,
                                                test_size=0.2,
                                                random_state=20)

In [21]:
# X_train

# 2. Build the Model

In [15]:
#LogisticRegression

from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train,y_train)

LogisticRegression()

# 3. Check the quality of the model

In [16]:
# Lets assume SL = 0.1 , CL = 0.9

print("Training Score: {}".format(model.score(X_train,y_train)))
print("Testing Score: {}".format(model.score(X_test,y_test)))

Training Score: 0.640625
Testing Score: 0.65


In [ ]:
# test_score > trai_score and test_score sholud > CL
# by seeing the test to train, it s a generalised moddel, but based on the CL values , this model gets reject.
# but check for better random state value for shuffling the data to get good accuracy of the model.

# Random State 
#### 1. randamization of data means shuffling the data
#### 2. Shuffling does affects the quality of the model

In [23]:
# Try By Changing the Value of Random State

CL = 0.9

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

for i in range(201,1001):
    X_train,X_test,y_train,y_test = train_test_split(features,
                                                label,
                                                test_size=0.2,
                                                random_state=i)
    model = LogisticRegression()
    model.fit(X_train,y_train)
    
    train_score = model.score(X_train,y_train)
    test_score = model.score(X_test,y_test)
    
    if test_score > train_score and test_score > CL:
        print("Testing Score {} Training Score {} RandomState {}".format(test_score,train_score,i))

Testing Score 0.9125 Training Score 0.834375 RandomState 314


In [27]:
CL = 0.9

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

# Max range suggested is less than equal to no of record in main dataset
# In this case range(1,401) should be the ideal case !!!!
for i in range(1,501):
    X_train,X_test,y_train,y_test = train_test_split(features,
                                                label,
                                                test_size=0.2,
                                                random_state=i)
    model = KNeighborsClassifier(n_neighbors=5)
    model.fit(X_train,y_train)
    
    train_score = model.score(X_train,y_train)
    test_score = model.score(X_test,y_test)
    
    if test_score > train_score and test_score > CL:
        print("Testing Score {} Training Score {} RandomState {}".format(test_score,train_score,i))

Testing Score 0.9125 Training Score 0.86875 RandomState 192
Testing Score 0.9375 Training Score 0.85 RandomState 323


In [32]:
model

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [34]:
#age,es

age = int(input("Enter Age: "))
es = int(input("Enter Estimated Salary: "))
features = np.array([[age,es]])

purchased = model.predict(features)
print("Customer : {}".format(purchased))

Enter Age:  23
Enter Estimated Salary:  234


Customer : [0]


In [35]:
model.coef_

array([[2.08010318e-01, 3.04036003e-05]])

In [36]:
model.intercept_

array([-11.02502264])

In [40]:
#Probabilities
model.predict_proba(np.array([[34,234567]]))

array([[0.03996332, 0.96003668]])

In [23]:
#Probabilities
model.predict_proba(np.array([[34,234567]]))[0]

array([0.65511123, 0.34488877])

In [24]:
#Probabilities
model.predict_proba(np.array([[34,234567]]))[0][0]

0.6551112349608477

In [25]:
#Probabilities
model.predict_proba(np.array([[34,234567]]))[0][0]>0.7

False

In [33]:
if model.predict_proba(np.array([[34,234567]]))[0][0]>0.7:
    return 1
else:
    return 0


SyntaxError: 'return' outside function (<ipython-input-33-92849dcdfa1c>, line 2)

In [44]:
#Custom Threshold Logic
#If Domain say if Probability Value is greater than 0.7 then Label - 1
# Else Label - 0

if model.predict_proba(np.array([[34,234567]]))[0][0] > 0.7:
    return 1
else:
    return 0


0.0399633193622585

In [ ]:
def domainPredict(prob_0):
    if prob_0 > 0.7:
        return 1
    else:
        return 0

In [41]:
#Label
model.predict(np.array([[34,234567]]))

array([1])

In [34]:
?model.predict

Signature: model.predict(X)
Docstring:
Predict class labels for samples in X.

Parameters
----------
X : array-like or sparse matrix, shape (n_samples, n_features)
    Samples.

Returns
-------
C : array, shape [n_samples]
    Predicted class label per sample.
File:      c:\users\davea\anaconda3\lib\site-packages\sklearn\linear_model\_base.py
Type:      method


In [1]:
#?model

In [2]:
#?KNeighborsClassifier